bodies:
- BODY base
- BODY big_ring_visual
- BODY CameraFrame
- BODY wire_visual
joints: []
high resolution path: ./high_res/
low resolution path: ./low_res/
ignore inter-collision: false
namespace: /ambf/env/phantom/
BODY base:
  name: base
  mesh: base.OBJ
  collision mesh type: CONVEX_HULL
  mass: 0.0
  inertia:
    ix: 0.0
    iy: 0.0
    iz: 0.0
  collision margin: 0.001
  scale: 1.0
  location:
    position:
      x: 0.03315
      y: 0.16777
      z: 0.70662
    orientation:
      r: 0.0
      p: -0.0
      y: 0.0
  inertial offset:
    position:
      x: 2.45127
      y: 2.89562
      z: 0.24572
    orientation:
      r: 0
      p: 0
      y: 0
  passive: false
  publish children names: false
  publish joint names: false
  publish joint positions: false
  friction:
    rolling: 0.0
    static: 0.5
  restitution: 0.1
  damping:
    angular: 0.1
    linear: 0.04
  visible: true
  collision groups: []
  use material: false
  color components:
    ambient:
      level: 1.0
    diffuse:
      b: 0.8
      g: 0.8
      r: 0.8
    specular:
      b: 0.4
      g: 0.4
      r: 0.4
    transparency: 1.0
BODY big_ring_visual:
  name: big_ring_visual
  mesh: big_ring_visual.OBJ
  collision mesh type: CONCAVE_MESH
  mass: 1.0
  collision margin: 0.001
  scale: 1.0
  location:
    position:
      x: 0.07783
      y: 0.16599
      z: 0.7145
    orientation:
      r: 0.0
      p: -0.0
      y: 0.0
  inertial offset:
    position:
      x: 0.0
      y: 0.0
      z: 0.0
    orientation:
      r: 0
      p: 0
      y: 0
  passive: false
  publish children names: false
  publish joint names: false
  publish joint positions: false
  friction:
    rolling: 0.0
    static: 0.5
  restitution: 0.1
  damping:
    angular: 0.1
    linear: 0.04
  visible: true
  collision groups: []
  use material: false
  color components:
    ambient:
      level: 1.0
    diffuse:
      b: 0.8
      g: 0.8
      r: 0.8
    specular:
      b: 0.4
      g: 0.4
      r: 0.4
    transparency: 1.0
BODY CameraFrame:
  name: CameraFrame
  mesh: ''
  collision mesh: ''
  collision mesh type: ''
  mass: 0.0
  inertia:
    ix: 0.0
    iy: 0.0
    iz: 0.0
  collision margin: 0.001
  scale: 1.0
  location:
    position:
      x: 0.03065
      y: 0.24923
      z: 0.81246
    orientation:
      r: 0.70595
      p: -0.0
      y: 3.14159
  inertial offset:
    position:
      x: 0
      y: 0
      z: 0
    orientation:
      r: 0
      p: 0
      y: 0
  passive: false
  color: random
  publish children names: false
  publish joint names: false
  publish joint positions: false
BODY wire_visual:
  name: wire_visual
  mesh: wire_visual.OBJ
  collision mesh: wire_collision_allchunks.OBJ
  collision mesh type: CONCAVE_MESH
  mass: 0.0
  inertia:
    ix: 0.0
    iy: 0.0
    iz: 0.0
  collision margin: 0.001
  scale: 1.0
  location:
    position:
      x: 0.0
      y: 0.16863
      z: 0.75989
    orientation:
      r: 0.0
      p: -0.0
      y: 0.0
  inertial offset:
    position:
      x: 0.0
      y: 0.0
      z: 0.0
    orientation:
      r: 0
      p: 0
      y: 0
  passive: false
  publish children names: false
  publish joint names: false
  publish joint positions: false
  friction:
    rolling: 0.0
    static: 0.5
  restitution: 0.1
  damping:
    angular: 0.1
    linear: 0.04
  visible: true
  collision groups: []
  use material: false
  color components:
    ambient:
      level: 1.0
    diffuse:
      b: 0.8
      g: 0.8
      r: 0.8
    specular:
      b: 0.4
      g: 0.4
      r: 0.4
    transparency: 1.0
